### ISSUE TITLE
cannot run GoPS on iterm2 mac mojave

### ISSUE THREAD

**Issue by dhiemaz** [noxer/gops#6]
I am using MacOS mojave with iterm2 and zsh as shell. What I do : 
1. go get -u github.com/noxer/gops
2. update my zsh configuration (.zshrc) as follow

`export PATH="/usr/local/opt/mysql-client/bin:$PATH"`
`export PATH="/Users/dimas/go/bin:$PATH"`
  
`setopt PROMPT_SUBST`
`PROMPT='$(gops -s zsh)'`

3. applied the update

`source ~/.zshrc`

There is nothing happens in my terminal. 

But when I manually run gops using command `gops -s zsh` then it print 

`%{%} dimas@MacBook-Air %{%}%{%} ~ %{%}%{%} %`

and then get back to zsh shell.

**Comment by noxer** [comment]
That is strange. Is there maybe some other component overwriting the prompt? What does `echo $PROMPT` say for you?

**Comment by dhiemaz** [comment]
@noxer here is the output for `echo $PROMPT` 

![Screenshot 2022-02-11 at 03 29 05](https://user-images.githubusercontent.com/6150781/153491242-df36a00f-30e6-412a-a26d-93722169f868.png)

**Comment by noxer** [comment]
Okay, that is wrong. When you put `PROMPT='$(gops -s zsh)'` directly into your shell, it should work. There seems to be something that replaces the prompt after you are trying to set it to GoPS.

**Comment by noxer** [comment]
Closed due to old age. Feel free to reopen if the problem persists.
